### ISSUE TITLE
Please transfer all issues to the istio/istio repo

### ISSUE THREAD

**Issue by geeknoid** [istio/installer#155]
Open each issue and select Transfer Issue in the bottom right.

Once all issues are transferred, we'll disable the Issues feature in this repo.

**Comment by richardwxn** [comment]
BTW do we need a new label in istio/istio repo for installer specific issue after transferring

**Comment by geeknoid** [comment]
You can add an area/environments/installer label if you'd like.

*From: *Xinnan Wen <notifications@github.com>
*Date: *Fri, May 10, 2019 at 10:45 PM
*To: *istio/installer
*Cc: *Martin Taillefer, Author

BTW do we need a new label in istio/istio repo for installer specific issue

**Comment by howardjohn** [comment]
When did we decide to do this?

**Comment by geeknoid** [comment]
TOC as part of the review of the refreshed issue policy.

*From: *John Howard <notifications@github.com>
*Date: *Sat, May 11, 2019 at 10:12 AM
*To: *istio/installer
*Cc: *Martin Taillefer, Author

When did we decide to do this?

**Comment by howardjohn** [comment]
I must have missed that one. The reason I ask is because all of these issues (and especially the tools ones) are in context. The issues you moved from tools make no sense (need ci to build images, for example is a weird issue to have in Istio/Istio but normal to have in tools). It is also a lot easier to manager here.

If the to decided then find with me, I'm curious if the docs repo will be doing the same

**Comment by geeknoid** [comment]
We'll have three places for issues. istio/istio, istio/istio.io, and
istio/community. All other repos should have their Issues feature turned
off.

*From: *John Howard <notifications@github.com>
*Date: *Sun, May 12, 2019 at 7:00 AM
*To: *istio/installer
*Cc: *Martin Taillefer, Author

I must have missed that one. The reason I ask is because all of these

**Comment by jkbschmid** [comment]
Agree with @howardjohn that keeping issues here makes them more easily manageable. If the decision is set then at least having an 'area/environments/installer' label would be great.

**Comment by costinm** [comment]
How about: since  we are so close to a release and we have been using this process before TOC decided to change, we keep using it as an experiment. 

After 1.2 is released - we can do a survey and compare the time to close bugs and other metrics - and get developer feedback. 

It is generally a good idea to get more data...

**Comment by costinm** [comment]
My point is we've been using the issues quite a bit before TOC decided - and there is no major urgency that I know to spend time moving stuff around. For new repos that are created - sure, they should follow the new process. And when we are not under time pressure ( one week to freeze, one month release ) - we can move stuff around.

**Comment by geeknoid** [comment]
We've done this experiment previously and we want to manage issues in a
central location.

*From: *Costin Manolache <notifications@github.com>
*Date: *Tue, May 14, 2019 at 1:44 PM
*To: *istio/installer
*Cc: *Martin Taillefer, Author

My point is we've been using the issues quite a bit before TOC decided -

**Comment by fpesce** [comment]
@geeknoid I've created an area/installer label and have transferred all opened issues (and a couple closed issues to reflect progression on Epic).
Label is area/installer if this is not a correct label (Installer does not have a workgroup so I suppose it might not be the best naming), then re-open this issue to suggest a better name.
