### ISSUE TITLE
Inconsistency in monitorPort variable and hardcoded value

### ISSUE THREAD

**Issue by ericvn** [istio/installer#97]
Looking at the various files in this repo, I see that there is a 
```# monitoring port used by mixer, pilot, galley
  monitoringPort: 15014
```
in global.yaml

This value is used in istio-control/istio-config/templates/deployment.yaml
```
          - --monitoringPort={{ .Values.global.monitoringPort | default "15014" }}
```
which allows one to set the galley monitoring port by overriding the variable, but note that the service port itself is hardcoded to 15014.

There are many location in the files where the port is hardcoded. Some examples:
istio-control/istio-config/templates/service.yaml
istio-policy/templates/deployment.yaml
istio-policy/templates/service.yaml
istio-telemetry/mixer-telemetry/templates/deployment.yaml
istio-telemetry/mixer-telemetry/templates/service.yaml
security/citadel/templates/service.yaml

_In the later files, a user trying to override the _monitoringPort_ value will be unsuccessful._

When comparing this to **1.1.x**, some of the files do use the variable:
install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml
install/kubernetes/helm/istio/charts/galley/templates/service.yaml
install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml
install/kubernetes/helm/istio/charts/mixer/templates/service.yaml
install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml
install/kubernetes/helm/istio/charts/pilot/templates/service.yaml
install/kubernetes/helm/istio/charts/security/templates/deployment.yaml
install/kubernetes/helm/istio/charts/security/templates/service.yaml

_The 1.1 changes for galley, mixer, and pilot were in https://github.com/istio/istio/pull/10019. So in Release 1.1, it is possible to install with an override and use a different monitoringPort._

So, we have a potential regression in functionality going from 1.1 to 1.2. We also have some inconsistency in when the value will be used.

Discussion:
  - Should the value hardcoded? I know when working on a PR for 1.1, I has told the ports were hardcoded, so I left the inconsistency in the PR (some things used the variable and others not), and worked on a new PR to change back to hardcode values: https://github.com/istio/istio/pull/12128 . That PR was never merged and has become stale. 
    - If the values should be hardcoded, understand that we are regressing some function that shipped in 1.1.
  - Depending on the answer, a PR should created to either move the values to the variable a constant.

I will gladly do the work once I know which way to go with it.

**Comment by howardjohn** [comment]
Costin and I think we should hardcode it. There is pretty much no reason to want to set this option, and it just leads to complexity. It was originally added because our monitoring port conflicted with Kafka - 15014 should not have similar issues. If they REALLY want to modify it, then can with Kustomize. 

FWIW, here are the backwards incompatible changes we made in 1.1 https://istio.io/docs/reference/config/installation-options-changes/#removed-configuration-options

**Comment by ericvn** [comment]
@howardjohn Would it make sense to hardcode and remove the option in the 1.1 stream to match, or should 1.1 continue to use the variable forcing the backwards incompatible change only on the 1.2 boundary? I'm thinking the later.

**Comment by howardjohn** [comment]
I don't think it is worth the effort to change 1.1

It is also better to make a backwards incompatible change in 1.x release then 1.x.x, so probably no changes needed

**Comment by ericvn** [comment]
I had a PR in 1.1 to hardcode values, but it was never merged before 1.1 was released. So not hard to actually make a change, probably just a rebase, but agree that we should NOT break things in the 1.1.x stream at this point.  Maybe @linsun. 

I'll see if there is more discussion, but I think the current answer is close my 1.1 PR and create a small PR here to remove the few remaining pieces of the variable (will do that shortly) but we can hold until this discussion is complete.

**Comment by howardjohn** [comment]
Sorry forgot to mention, it should be all cleaned up in https://github.com/istio/installer/pull/91

**Comment by ericvn** [comment]
OK. Guess I spent some time for nothing on that then. Except maybe my `make test` failed again with my similar changes.

**Comment by costinm** [comment]
We can do some cleanup - keep in mind that the plan is to recommend installing the components in different namespaces to improve security and shift traffic to the new control plane. 

So unlike 1.0 -> 1.1 upgrade, changing install options will not break  production system running 1.1 - since 1.2 will be installed in the separate ns and user can test and move back workloads in case of problems. 

We want to minimize pain - and options that are commonly used should not be changed arbitrarily, but 
thing that are not commonly used ( like changing monitoringPort ) or can be configured with kustomize are safe to cleanup.

**Comment by howardjohn** [comment]
Should be fixed now
